<?
$session = session();
$headers = response()->headers();
?>

<h2 style="margin-top: 30px">Request</h2>
<p><b>Parameters</b>: <pre><? print_r($request->params()) ?></pre></p>

<p><a href="#" onclick="document.getElementById('session_dump').style.display='block'; return false;">Show session dump</a></p>
<div id="session_dump" style="display:none"><pre><? print_r((array)$session) ?></pre></div>

<p><a href="#" onclick="document.getElementById('env_dump').style.display='block'; return false;">Show env dump</a></p>
<div id="env_dump" style="display:none"><pre><? print_r($request) ?>></pre></div>


<h2 style="margin-top: 30px">Response</h2>
<p><b>Headers</b>: <pre><?= count($headers) ? print_r($headers, true) : 'None' ?></pre></p>
